# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='serviceType',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='webURL',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
