# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20200613_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
