# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-14 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavouriteshop',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='userfavouriteshop',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavouriteShop',
        ),
    ]
